<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{block name="headTitle"}{/block} - OMG</title>
    <!-- Bootstrap Core CSS -->
    {css href="/static/sbadmin2/vendor/bootstrap/css/bootstrap.min.css" /}
    <!-- MetisMenu CSS -->
    {css href="/static/sbadmin2/vendor/metisMenu/metisMenu.min.css" /}
    <!-- Custom CSS -->
    {css href="/static/sbadmin2/dist/css/sb-admin-2.css" /}
    <!-- Custom Fonts -->
    {css href="/static/sbadmin2/vendor/font-awesome/css/font-awesome.min.css" /}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{block name="body"}
<div id="wrapper">
{include file="nav" /}
    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            {block name="container"}{/block}
        </div>
    </div>
</div>
{/block}
<!-- /#wrapper -->

<!-- jQuery -->
{js href="/static/sbadmin2/vendor/jquery/jquery.min.js" /}
<!-- Bootstrap Core JavaScript -->
{js href="/static/sbadmin2/vendor/bootstrap/js/bootstrap.min.js" /}
<!-- Metis Menu Plugin JavaScript -->
{js href="/static/sbadmin2/vendor/metisMenu/metisMenu.min.js" /}
<!-- Custom Theme JavaScript -->
{js href="/static/sbadmin2/dist/js/sb-admin-2.js" /}

{block name="bottom"}{/block}
</body>
</html>
