<?php
$nav_menus = \app\common\service\Dom::getApiControllers();
?>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{:url('@docs')}"> 文档后台</a>
    </div>
    <!-- /.navbar-header -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                {/*<li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                    </div>
                    <!-- /input-group -->
                </li>*/}
                <li>
                    <a href="{:url('@docs')}"><i class="fa fa-home fa-fw"></i> Home</a>
                </li>
                <?php if(!empty($nav_menus)): ?>
                <?php $i = 1; ?>
                <?php foreach($nav_menus as $nav_title => $nav_menu):?>
                <?php $j = 1; ?>
                <li>
                    <a href="#"><i class="fa fa-sitemap fa-fw"></i> {$nav_menu.title}<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <?php if(!empty($nav_menu['action'])):  ?>
                        <?php foreach($nav_menu['action'] as $nav_action):?>
                        <li>
                            <a href="<?=url('@docs/info',['c'=>$nav_action['controller'], 'a'=>$nav_action['method']]); ?>"> {$i}-{$j++}. {$nav_action.title}</a>
                        </li>
                        <?php endforeach; endif; ?>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <?php $i++; ?>
                <?php endforeach; endif; ?>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>