{extend name="blank" /}

{block name="pageContent"}
<div class="x_panel">
    <div class="x_content">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>标题</th>
                    <th>说明</th>
                    <th>活动时间</th>
                    <th>发布时间</th>
                    <th>展示方式</th>
                    <th>#</th>
                </tr>
                </thead>
                <tbody>
                {foreach $list as $act}
                <tr data-id="{$act->id}" class="data-row">
                    <th scope="row">{$act->id}</th>
                    <td>{$act->subject}</td>
                    <td>{$act->intro}</td>
                    <td>{$act->start_time|date='Y-m-d H:i',###} - {$act->end_time|date='Y-m-d H:i',###}</td>
                    <td>{$act->publish_at|date='Y-m-d H:i',###}</td>
                    <td>{$act->show_type==1?='Group'}</td>
                    <td>
                        <a class="btn btn-xs btn-info" href="/open/activity/{$act->id}.html"><i class="fa fa-eye"></i> See</a>
                    </td>
                </tr>
                {/foreach}
                </tbody>
            </table>
            <div class="col-xs-12">
                <div class="pull-right">
                    {include file="paginate"}
                </div>
            </div>
        </div>
    </div>
</div>
{/block}