{extend name="blank" /}


{block name="pageContent"}
<div class="x_panel question-lister">
    <div class="x_title">
        <div class="pull-left">
            <button class="btn btn-success btn-editQ"><i class="fa fa-plus-circle"></i> 添加</button>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        {FOREACH $list AS $row}
        <table class="table table-striped jambo_table bulk_action" data-id="{$row->id}">
            <thead>
            <tr>
                <th>{$row->id}</th>
                <th>{$row->view_key}</th>
                <th>{$row->title}</th>
                <th>
                    <button class="btn btn-xs btn-primary btn-editQ" data-id="{$row->id}">编辑</button>
                    <button class="btn btn-xs btn-success btn-editOpt" data-qid="{$row->id}">添加选项</button>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr class="thead-r2">
                <td>Value</td>
                <td>Detail</td>
                <td>Pic</td>
                <td style="width: 20%">#</td>
            </tr>
            {FOREACH $row->opts AS $opt}
            <tr data-id="{$opt->id}">
                <td>{$opt->getData('value')}</td>
                <td>{$opt->detail}</td>
                <td onclick="showBigPic('{$opt->pic}')">{$opt->pic}</td>
                <td>
                    <span class="btn-editOpt" data-qid="{$row->id}" data-id="{$opt->id}">编辑</span>
                    <span class="pl-1 text-danger btn-delOpt" data-id="{$opt->id}">删除</span>
                </td>
            </tr>
            {/FOREACH}
            </tbody>
        </table>
        {/FOREACH}
        <div class="col-xs-12">
            <div class="pull-right">
                {include file="paginate"}
            </div>
        </div>
    </div>
</div>


<!-- 模态框（编辑问题） -->
<div class="modal fade" id="editQModal" tabindex="-1" role="dialog" aria-labelledby="editQModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="editQModalLabel">编辑问题</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    {:token()}
                    <input type="hidden" name="subject_id" value="{$subject->id}">
                    <input type="hidden" id="editQ_id" name="_id">
                    <div class="form-group">
                        <label for="editQ_title" class="col-sm-2 control-label">问题</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="editQ_title" name="title" placeholder="输入问题">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="editQ_key" class="col-sm-2 control-label">模板名</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="editQ_key" name="view_key" placeholder="QM-1">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary btn-submit">提交</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>


<!-- 模态框（编辑选择项） -->
<div class="modal fade" id="editOptModal" tabindex="-1" role="dialog" aria-labelledby="editOptModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="editOptModalLabel">编辑问题</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form">
                    {:token()}
                    <input type="hidden" name="subject_id" value="{$subject->id}">
                    <input type="hidden" id="editOpt_qid" name="question_id">
                    <input type="hidden" id="editOpt_id" name="_id">
                    <input type="hidden" id="editOpt_pic" name="pic">
                    <div class="form-group">
                        <label for="editOpt_value" class="col-sm-2 control-label">Value</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" id="editOpt_value" name="value" placeholder="选项的值">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="editOpt_detail" class="col-sm-2 control-label">Detail</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="editOpt_detail" name="detail" placeholder="选项说明">
                        </div>
                    </div>
                </form>
                <div class="dropzone" id="optPic-box">
                    <div class="dz-default dz-message"><span>PIC</span></div>
                    <div class="fallback">
                        <input name="file" type="file" multiple />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary btn-submit">提交</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>
{/block}

{block name="head"}
<!-- Dropzone.js -->
<link href="/static/g/vendors/dropzone/dist/min/dropzone.min.css" rel="stylesheet">
{/block}

{block name="bottom"}
<script src="/static/g/vendors/dropzone/dist/min/dropzone.min.js"></script>
<script src="/static/js/open/common.js"></script>
<script src="/static/js/open/question.js"></script>
{/block}