
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> SDK | Pstore | 结合测试</title>
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="/static/sbadmin2/vendor/bootstrap/css/bootstrap.min.css" />
    <!-- MetisMenu CSS -->
    <link rel="stylesheet" type="text/css" href="/static/sbadmin2/vendor/metisMenu/metisMenu.min.css" />
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="/static/sbadmin2/dist/css/sb-admin-2.css" />
    <!-- Custom Fonts -->
    <link rel="stylesheet" type="text/css" href="/static/sbadmin2/vendor/font-awesome/css/font-awesome.min.css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<style>
    a, a:visited {color:#ffffff; text-decoration: none; }
    a:link, a:hover {color:#e0e0e0; text-decoration:none; }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-body">
                    <div class="well well-lg" style="background-color: rebeccapurple;">
                        <h1><a href="{:url('/docs')}">API Docs</a></h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-body">
                    <div class="well well-lg" style="background-color: yellowgreen;">
                        <h1><a href="{:url('/open')}">Open Admin</a></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- /#wrapper -->

<!-- jQuery -->
<script type="text/javascript" src="/static/sbadmin2/vendor/jquery/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script type="text/javascript" src="/static/sbadmin2/vendor/bootstrap/js/bootstrap.min.js"></script>
<!-- Metis Menu Plugin JavaScript -->
<script type="text/javascript" src="/static/sbadmin2/vendor/metisMenu/metisMenu.min.js"></script>
<!-- Custom Theme JavaScript -->
<script type="text/javascript" src="/static/sbadmin2/dist/js/sb-admin-2.js"></script>


</body>
</html>
