<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="/static/g/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/g/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/g/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/static/g/vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/static/g/build/css/custom.min.css" rel="stylesheet">
</head>
<body class="login">
<div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                <form id="loginForm">
                    <h1>Login Form</h1>
                    <div>
                        <input type="text" class="form-control" name="account" placeholder="Username" required="" />
                    </div>
                    <div>
                        <input type="password" class="form-control" name="password" placeholder="Password" required="" />
                    </div>
                    <div>
                        <button type="button" class="btn btn-default btn-submit">Log in</button>
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator">

                        <div class="clearfix"></div>
                        <br />

                        <div>
                            <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
                            <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>

<script src="/static/g/vendors/jquery/dist/jquery.min.js"></script>
<script src="/static/js/crypto-js-3.1.9-1/crypto-js.js"></script>
<script src="/static/js/jquery.serializejson.min.js"></script>
<script type="text/javascript">
    function encrypt(content, key) {
        key = CryptoJS.enc.Utf8.parse(key);
        var encryptResult = CryptoJS.AES.encrypt(content, key, {
            //iv: key,
            mode: CryptoJS.mode.ECB,
            padding: CryptoJS.pad.Pkcs7
        });
        return encryptResult.toString();
    }

    $(function () {
        var form = $('#loginForm');
        var formToken = '{$Request.token}';
        form.find('.btn-submit').click(function () {
            var content = JSON.stringify( form.serializeJSON() );
            var data = encrypt(content, formToken);

            $.post('/open/login', {__token__: formToken, data: data}, function (resp) {
                if(resp.code == 1) {
                    window.location.href= '/open.html';
                } else {
                    formToken = resp.data;
                    alert(resp.msg);
                }

            });
        });
    });
</script>
</body>
</html>
