<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="/static/g/images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                {/* <h3>General</h3>*/}
                <ul class="nav side-menu">
                    {FOREACH $menu AS $m}
                    {EMPTY name="m.children"}
                    <li> <a href="{$m.item->path}"><i class="{$m.item->class_icon}"></i><span class="hide-menu">{$m.item->name|strip_tags}</span></a></li>
                    {ELSE/}
                    <li><a><i class="{$m.item->class_icon}"></i> {$m.item->name} <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            {FOREACH $m.children AS $c}
                            <li><a href="{$c->path}">{$c->name|strip_tags}</a></li>
                            {/FOREACH}
                        </ul>
                    </li>
                    {/EMPTY}
                    {/FOREACH}
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>
