<form>
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
            <input type="text" class="form-control" name="Search" placeholder="Search for...">
            <span class="input-group-btn">
                      <button class="btn btn-default" type="submit">Go!</button>
                    </span>
        </div>
    </div>
</form>
<!--<form class="form-horizontal">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
            <select class="form-control" style="width: 30%;">
                <option>All</option>
                <option>1</option>
                <option>2</option>
            </select>
            <input type="text" class="form-control" style="width: 70%;" name="Search" placeholder="Search for...">
            <span class="input-group-btn">
                      <button class="btn btn-default" type="submit">Go!</button>
                    </span>
        </div>
    </div>
</form>-->