<?php
return [
    'sex' => '性别：1男，2女',
    'attend_times' => '已签到次数',
    'attend_today' => '今日签到数',
    'is_attended' => '是否已签到',
    'is_finished' => '是否已完成',
    'is_show_qrcode' => '是否显示二维码',
    'is_withdrawable' => '是否可提现',
    'is_share_group_success' => '是否分享群成功',
    'is_valid' => '是否有效',
    'is_sleepy' => '是否为不活跃用户',
    'auto_withdraw' => '是否为直接提现',
    'withdraw_status' => '提现状态：0，未提现，1.已申请，审核中,2.已完成',
    'rate_rmb_1000' => '1000积分≈？元',
    'operable_amount' => '可操作金额',
    'used_amount' => '已提现金额',
    'point' => '积分，ABE',
    'referrer_success_num' => '成功邀请数, 有效邀请数',
    'is_audit_during' => '小程序是否在审核期间',
    'referrer_lv1' => '一级邀请',
    'referrer_lv2' => '二级邀请',
    'real_referrer_lv1' => '一级有效邀请',
    'real_referrer_lv2' => '二级有效邀请',
    'income_amount' => '收益金额：分',
    'income_point' => '收益积分',
    'withdraw_minPoint' => '提现最小积分',
    'remaining_time' => '剩余时间',
    'has_share' => '存在分享记录'
];